name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config rdma-core
    - name: Clippy
      run: cargo clippy --all-targets
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Run tests
      run: cargo test --all-targets --verbose
    - name: Run sys tests
      run: |
        cd rdmacm-sys
        cargo test --verbose
